name: Deno Test

on:
  push:
    tags: [ "0.8" ]
    branches: [ "0.x" ]
  pull_request:
    tags: [ "0.8" ]
    branches: [ "0.x" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.41.0
      - run: deno test

