name: Deno Test

on:
  push:
    tags: [ "0.10" ]
    branches: [
        "0.x",
        "master"
      ]
  pull_request:
    tags: [ "0.10" ]
    branches: [
        "0.x",
        "master"
      ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.0-rc2
      - run: deno test

